### ISSUE TITLE
Couple of things...

### ISSUE THREAD

**Issue by t3chn0r** [hlsolutions/jquery-autosuggest#14]
Hello, I'm new to this plugin so bear with me... :)

I've been doing some tests and everything works fine except that my original input field is not being populated with the selected options.

So, my field looks like this:

```
<input tabindex="1" type="text" name="_recipients" id="_recipients" value="" autofocus>
```

And after calling .autoSuggest() on it I was seeing something like this:

```
<li class="as-original" id="as-original-28">
    <input disabled-placeholder="Enter name here..." class="as-input" autocomplete="off" tabindex="1" name="_recipients" id="as-input-28" value="" autofocus="" type="text">
    <input value="" class="as-values" name="as_values_28" id="as-values-28" type="hidden">
</li>
```

I did changes to the plugin so everything will work transparently and it now looks like this:

```
<li class="as-original" id="as-original-28">
    <input disabled-placeholder="Enter name here..." class="as-input" autocomplete="off" tabindex="1" name="as-input-28" id="as-input-28" value="" autofocus="" type="text">
    <input value="" class="as-values" name="_recipients" id="_recipients" type="hidden">
</li>
```

Like I said, I'm new to this plugin so I wasn't sure if I was missing something as to how to get the selected values once the form is submitted.
Also, I went through the documentation and couldn't find anything regarding the setting of parameters globally. I would like to translate the text elements like startText, emptyText, and limitText based on the user connected to the application. I can do this with all the plugins currently being used but I can't see how this can be done with autoSuggest() so translations are specified only once and I don't need to pass them for every input field.

Regards,
t3chn0r

**Comment by knalli** [comment]
Hi @t3chn0r, be not afraid to ask.

Could you please provide a more detailed example, e.g. as a gist or perhaps even Fiddle or so?

I'd mocked your described example a little bit dirty and got no issue.. I think I don't get what your problem is.
![Bildschirmfoto 2013-02-22 um 21 26 44](https://f.cloud.github.com/assets/65389/186495/5dd603a2-7d2e-11e2-973d-05399e645d01.png)

Global parameters are not supported, currently. If you plan to integrate this feature, feel free to PR that one. I will create an _enhancement issue_, but actually without any date target.

**Comment by knalli** [comment]
Global parameters: We had actually used a custom option builder factory. Because of this, we had not required this.

**Comment by t3chn0r** [comment]
Hello @knalli, thanks for your quick response. Actually what you are seeing is exactly what I'm talking about, if you see the field where the values are being stored in a field with a random generated name and id based on the element ID. I think it will be more natural for this field to have the name and id from the original field that was autoSuggested().

I did the necessary changes to do this (it's only a couple of lines), I can create a pull request if you want, I'm always glad to help.

Again, the plugin works but on the server side so expect to access the selected values by using the name of the field that was there originally and not really going crazy trying to figure out what is the name of the field holding the values (that I think it can really messy if you have more than one autoSuggest() field in the same form).

Regards,
t3ch

PS: Thanks for [#15](https://github.com/hlsolutions/jquery-autosuggest/issues/15)! Really appreciate it!

**Comment by knalli** [comment]
Yep, this is correct. We'd forked this one originally and improved it later with security and functionality. However, the naming issue of the field is indeed not be very comfortable. We don't touch this because we wrapped some glue code around it....

So, yes: If you want to get the values you have to use some magic selectors. We'd internally switched to a more modern https://github.com/loopj/jquery-tokeninput

**Comment by t3chn0r** [comment]
Thanks, I will take a look at the other plugin then even though I already have this one working like I need...

Edit: Just took a quick look at the other plugin and tried to do a quick test but it seems to have several issues... I will submit a pull-request with my changes to fix the variable name thing in case you want to merge it.
